### ISSUE TITLE
2018.07.11 记一次错误的解决( pre 标签)

### ISSUE THREAD

**Issue by YyzclYang** [YyzclYang/notes#19]
今天在尝试一个会动简历的小 demo ，因为要实现`CSS`代码输出在页面的同时改变页面的`CSS`，代码中涉及到很多的回车、空格及 Tab ，普通的标签会将连续的回车、空格及 Tab 缩成一个空格，会破坏代码的显示，这里就选择了`<pre>`标签，先来看看 MDN 上对`<pre>`的说明。

## `<pre>`

> HTML `<pre>` 元素表示预定义格式文本。在该元素中的文本通常按照原文件中的编排，以等宽字体的形式展现出来，文本中的空白符（比如空格和换行符）都会显示出来。(紧跟在 `<pre>` 开始标签后的换行符也会被省略)

从 MDN 上的解释，我们可以知道，`<pre>`标签可以完美解决`CSS`代码中回车、空格及 Tab 的显示问题。好了，就决定是你了。

然而，这里也为后面的一个 bug 埋下了隐患。

## demo 进行时

`<pre>`标签果然很厉害，什么回车、空格及 Tab ，一个都别想跑，别想偷懒，全部给我显示出来。

![](https://i.loli.net/2018/07/11/5b44f9be70a15.png)

从图中可以看到，除了`<pre>`标签之外，其余的标签均不能把多个连续的回车、空格及 Tab 显示出来。

## bug 出现

当我开开心心一步步地完成这个 demo 时，bug 出现了

![](https://i.loli.net/2018/07/11/5b44fa925631a.png)

为啥不换行，字符串都怼在一行了。你们有这么亲密吗？抱的这么紧。`<li>`标签默认是换行地啊，而且这里又不是英文

![](https://i.loli.net/2018/07/11/5b44fac6d0616.jpg)

## 尝试解决

好吧，既然 bug 出现了，还是好好想想怎么解决吧。

- `<li>`的宽度

一开始想到会不会`<li>`的宽度出了问题，立马打开开发者工具查看宽度，发现宽度并没有问题，字符串明显超出了宽度的界限。

![](https://i.loli.net/2018/07/11/5b450640ddca9.png)

在这种情况下，还是不死心，自己手动加一个宽度限制，结果并没有变化，看来不是宽度问题

![](https://i.loli.net/2018/07/11/5b450715c6689.png)

- `<li>`的属性

在这里又想到了会不会`<li>`属性在 Markdown 转 HTML 时暗中发生了变化，导致`<li>`出现了不换行。这时候又利用谷歌搜索他人遇到了各种情况，然后利用开发者工具尝试改各种属性，然而不管怎么改，不换行的情况屹然不动，稳如泰山。

- 加个`<div>`嵌套

换个思路，用一个`<div>`把文字包住试试，然而还是不行，字符串就像用强力胶粘住了一样，就是不分开。在这个`<div>`上动手脚，改宽度，改属性等等，都没用

- 其他方法

这时候又陆续尝试了其他的一些方式，但结果依然让人沮丧。

## 致命一击

这时候，突然想到`<pre>`标签，以前都没用过这个标签，会不会是它的问题？

说动就动，立马在开发者工具中把这个标签改成`<div>`。哇！

![](https://i.loli.net/2018/07/11/5b4509e98044a.png)

> kjsklajfklhaklfhask

哈哈，果然是它的问题，终于找出了问题所在了。但是又不能用`<div>`代替这个标签，不然在将内容逐步显示在页面上时，连续空格的问题就无法解决。

立马搜索下`<pre>`换行的问题，一下就找到了解决方案。

```CSS
pre { 
  white-space: pre-wrap; /*css-3*/ 
  white-space: -moz-pre-wrap; /*Mozilla,since1999*/ 
  white-space: -pre-wrap; /*Opera4-6*/ 
  white-space: -o-pre-wrap; /*Opera7*/ 
  word-wrap: break-word; /*InternetExplorer5.5+*/ 
} 
```

![](https://i.loli.net/2018/07/11/5b450adf84fff.png)

bingo！完美解决，可以安心睡觉了

## 体验

从遇到问题到解决问题，自己的思维方向换了好几次方向，所幸最后还是找到了问题所在。

通过这个问题的解决，追根到底，还是自己对基础知识掌握不够，对标签的属性不能完全掌握，在以后的学习中要避免这种情况。
